export interface Load {
  rr_number: string;
  load_number?: string;
  tm_number?: string;
  status_code: "active" | "published" | "completed" | "cancelled" | "archived";
  pickup_date: string;
  pickup_time?: string;
  pickup_window?: string;
  delivery_date: string;
  delivery_time?: string;
  delivery_window?: string;
  revenue: number | null;
  target_buy?: number | null;
  max_buy?: number | null;
  purchase: number | null;
  net: number | null;
  margin: number | null;
  equipment: string;
  customer_name?: string;
  customer_ref?: string;
  driver_name?: string;
  spot_bid?: number | null;
  fuel_surcharge?: number | null;
  docs_scanned?: string;
  invoice_date?: string;
  invoice_audit?: string;
  purch_tr?: number | null;
  net_mrg?: number | null;
  cm?: number | null;
  nbr_of_stops?: number | null;
  vendor_dispatch?: string;
  dispatcher_name?: string;
  total_miles: number | null;
  origin_city: string;
  origin_state: string;
  destination_city: string;
  destination_state: string;
  vendor_name?: string;
  updated_at: string;
  published: boolean;
}
