// Scraped from https://www.flatuicolorpicker.com/color-model/hsl-color-model/ (pages 2-12)
// Generated on 2025-11-08T03:13:23.756Z
// Add these to EXPANDED_COLORS in components/ui/AdvancedColorPicker.tsx

export const FLAT_UI_COLORS = [
  { name: "Menthol", value: "hsl(88, 77%, 78%)", category: "Greens" },
  { name: "Sol Spray", value: "hsl(166, 84%, 68%)", category: "Cyans" },
  { name: "Bizarre", value: "hsl(347, 33%, 89%)", category: "Special" },
  { name: "Primrose", value: "hsl(57, 69%, 77%)", category: "Yellows" },
  { name: "Cerise", value: "hsl(329, 75%, 56%)", category: "Special" },
  { name: "Daily Bush", value: "hsl(272, 61%, 34%)", category: "Pinks" },
  { name: "Burly Wood", value: "hsl(31, 60%, 73%)", category: "Oranges" },
  { name: "Green Pea", value: "hsl(171, 52%, 18%)", category: "Cyans" },
  { name: "Sulu", value: "hsl(76, 76%, 72%)", category: "Greens" },
  { name: "Teak", value: "hsl(43, 29%, 51%)", category: "Oranges" },
  { name: "Sunny", value: "hsl(59, 100%, 75%)", category: "Yellows" },
  { name: "Pearl Bush", value: "hsl(30, 25%, 91%)", category: "Neutrals" },
  { name: "Cruise", value: "hsl(181, 45%, 81%)", category: "Cyans" },
  { name: "Laser Canary", value: "hsl(84, 100%, 70%)", category: "Greens" },
  { name: "Stark White", value: "hsl(47, 38%, 78%)", category: "Yellows" },
  { name: "Light Wood", value: "hsl(3, 17%, 44%)", category: "Neutrals" },
  { name: "Persian Indigo", value: "hsl(261, 78%, 38%)", category: "Purples" },
  { name: "Santa Grey", value: "hsl(260, 5%, 65%)", category: "Neutrals" },
  { name: "Athens Gray", value: "hsl(240, 3%, 94%)", category: "Neutrals" },
  { name: "Teal Blue", value: "hsl(203, 92%, 19%)", category: "Blues" },
  { name: "Fuego", value: "hsl(74, 73%, 51%)", category: "Yellows" },
  { name: "Deep Cerise", value: "hsl(334, 63%, 50%)", category: "Special" },
  { name: "Catskill White", value: "hsl(195, 33%, 95%)", category: "Neutrals" },
  { name: "Endeavour", value: "hsl(223, 54%, 34%)", category: "Blues" },
  { name: "Cotton Cloth", value: "hsl(51, 80%, 90%)", category: "Yellows" },
  { name: "Lynx White", value: "hsl(120, 14%, 97%)", category: "Neutrals" },
  { name: "Melon Melody", value: "hsl(26, 93%, 78%)", category: "Oranges" },
  { name: "Lacquer Mauve", value: "hsl(322, 50%, 87%)", category: "Special" },
  { name: "Inchworm", value: "hsl(84, 92%, 71%)", category: "Greens" },
  { name: "Plain And Simple", value: "hsl(78, 51%, 90%)", category: "Greens" },
  { name: "Seaside Villa", value: "hsl(23, 39%, 85%)", category: "Oranges" },
  { name: "Lime Splash", value: "hsl(68, 51%, 71%)", category: "Yellows" },
  { name: "Alabaster", value: "hsl(34, 42%, 93%)", category: "Neutrals" },
  { name: "Sweetly", value: "hsl(336, 71%, 95%)", category: "Neutrals" },
  { name: "Interdimensional Blue", value: "hsl(248, 74%, 47%)", category: "Purples" },
  { name: "Atomic Tangerine", value: "hsl(15, 100%, 72%)", category: "Oranges" },
  { name: "Sauvignon", value: "hsl(28, 42%, 94%)", category: "Neutrals" },
  { name: "Thistle", value: "hsl(304, 15%, 79%)", category: "Neutrals" },
  { name: "Lavender Grey", value: "hsl(230, 30%, 85%)", category: "Blues" },
  { name: "Tasma", value: "hsl(89, 14%, 72%)", category: "Neutrals" },
  { name: "Linen", value: "hsl(25, 75%, 97%)", category: "Neutrals" },
  { name: "Ultramarine", value: "hsl(241, 91%, 45%)", category: "Purples" },
  { name: "Clear Day", value: "hsl(174, 100%, 96%)", category: "Neutrals" },
  { name: "Blue Marguerite", value: "hsl(242, 42%, 51%)", category: "Purples" },
  { name: "Chartreuse Yellow", value: "hsl(68, 96%, 51%)", category: "Yellows" },
  { name: "Blue Martine", value: "hsl(178, 82%, 44%)", category: "Cyans" },
  { name: "White Ice", value: "hsl(150, 70%, 96%)", category: "Neutrals" },
  { name: "Jagged Ice", value: "hsl(168, 46%, 85%)", category: "Cyans" },
  { name: "Buddha Gold", value: "hsl(48, 77%, 42%)", category: "Yellows" },
  { name: "Electrik Violet", value: "hsl(261, 92%, 51%)", category: "Purples" },
  { name: "Yellow Rose", value: "hsl(56, 100%, 50%)", category: "Yellows" },
  { name: "Blue Chalk", value: "hsl(263, 36%, 96%)", category: "Neutrals" },
  { name: "Pale Green", value: "hsl(130, 91%, 78%)", category: "Greens" },
  { name: "Pampa", value: "hsl(45, 22%, 93%)", category: "Neutrals" },
  { name: "Canary", value: "hsl(60, 100%, 81%)", category: "Yellows" },
  { name: "Jacarta", value: "hsl(246, 43%, 31%)", category: "Purples" },
  { name: "Satin Linen", value: "hsl(49, 22%, 90%)", category: "Yellows" },
  { name: "Navy", value: "hsl(240, 98%, 24%)", category: "Purples" },
  { name: "Red Orange", value: "hsl(8, 100%, 59%)", category: "Reds" },
  { name: "Paua", value: "hsl(235, 41%, 25%)", category: "Blues" },
  { name: "Laser Lemon", value: "hsl(70, 100%, 72%)", category: "Yellows" },
  { name: "Neon Blue", value: "hsl(229, 100%, 59%)", category: "Blues" },
  { name: "Minsk", value: "hsl(240, 41%, 33%)", category: "Purples" },
  { name: "Hippie Pink", value: "hsl(350, 46%, 47%)", category: "Special" },
  { name: "Snuff", value: "hsl(282, 21%, 88%)", category: "Pinks" },
  { name: "Whisper", value: "hsl(257, 23%, 94%)", category: "Neutrals" },
  { name: "Eggplant", value: "hsl(313, 19%, 37%)", category: "Neutrals" },
  { name: "Mountbatten Pink", value: "hsl(306, 13%, 57%)", category: "Neutrals" },
  { name: "Bittersweet", value: "hsl(7, 99%, 70%)", category: "Reds" },
  { name: "Ziggurat", value: "hsl(191, 40%, 82%)", category: "Cyans" },
  { name: "Blue Chill", value: "hsl(197, 88%, 36%)", category: "Blues" },
  { name: "Finn", value: "hsl(334, 39%, 31%)", category: "Special" },
  { name: "Pharlap", value: "hsl(351, 17%, 56%)", category: "Neutrals" },
  { name: "Pale Slate", value: "hsl(333, 10%, 79%)", category: "Neutrals" },
  { name: "Boston Blue", value: "hsl(193, 44%, 46%)", category: "Cyans" },
  { name: "Azure Radiance", value: "hsl(208, 100%, 51%)", category: "Blues" },
  { name: "Black Pearl", value: "hsl(230, 69%, 10%)", category: "Blues" },
  { name: "Governor Bay", value: "hsl(240, 60%, 42%)", category: "Purples" },
  { name: "Hint Of Red", value: "hsl(0, 19%, 95%)", category: "Neutrals" },
  { name: "Geyser", value: "hsl(175, 21%, 88%)", category: "Cyans" },
  { name: "Bahama Blue", value: "hsl(197, 100%, 29%)", category: "Blues" },
  { name: "Blue Dianne", value: "hsl(187, 47%, 21%)", category: "Cyans" },
  { name: "Golden Sand", value: "hsl(52, 85%, 69%)", category: "Yellows" },
  { name: "New Orleans", value: "hsl(43, 77%, 76%)", category: "Oranges" },
  { name: "Magic Mint", value: "hsl(152, 73%, 84%)", category: "Cyans" },
  { name: "Merino", value: "hsl(28, 48%, 94%)", category: "Neutrals" },
  { name: "Deep Blush", value: "hsl(346, 72%, 67%)", category: "Special" },
  { name: "Cerulean", value: "hsl(182, 87%, 39%)", category: "Cyans" },
  { name: "Fuzzy Wuzzy Brown", value: "hsl(355, 50%, 54%)", category: "Special" },
  { name: "Blumine", value: "hsl(207, 61%, 30%)", category: "Blues" },
  { name: "Aquamarine", value: "hsl(167, 98%, 74%)", category: "Cyans" },
  { name: "Pippin", value: "hsl(0, 100%, 95%)", category: "Neutrals" },
  { name: "Mulberry", value: "hsl(334, 44%, 54%)", category: "Special" },
  { name: "Moody Blue", value: "hsl(234, 44%, 66%)", category: "Blues" },
  { name: "Froly", value: "hsl(354, 80%, 73%)", category: "Special" },
  { name: "Falcon", value: "hsl(331, 12%, 41%)", category: "Neutrals" },
  { name: "Moon Glow", value: "hsl(54, 95%, 91%)", category: "Neutrals" },
  { name: "Light Buckthorn", value: "hsl(40, 94%, 58%)", category: "Oranges" },
  { name: "Medium Red Violet", value: "hsl(301, 47%, 40%)", category: "Special" },
  { name: "Mariner", value: "hsl(207, 64%, 48%)", category: "Blues" },
  { name: "White Smoke", value: "hsl(0, 0%, 93%)", category: "Neutrals" },
  { name: "Lynch", value: "hsl(211, 12%, 48%)", category: "Neutrals" },
  { name: "Pumice", value: "hsl(132, 6%, 83%)", category: "Neutrals" },
  { name: "Gallery", value: "hsl(0, 0%, 93%)", category: "Neutrals" },
  { name: "Silver Sand", value: "hsl(204, 8%, 76%)", category: "Neutrals" },
  { name: "Porcelain", value: "hsl(192, 15%, 94%)", category: "Neutrals" },
  { name: "Cascade", value: "hsl(184, 9%, 62%)", category: "Neutrals" },
  { name: "Iron", value: "hsl(197, 10%, 87%)", category: "Neutrals" },
  { name: "Edward", value: "hsl(180, 8%, 69%)", category: "Neutrals" },
  { name: "Cararra", value: "hsl(40, 10%, 94%)", category: "Neutrals" },
  { name: "Silver", value: "hsl(0, 0%, 75%)", category: "Neutrals" },
  { name: "Solitude", value: "hsl(207, 20%, 91%)", category: "Neutrals" },
  { name: "Pampas", value: "hsl(30, 14%, 95%)", category: "Neutrals" },
  { name: "Mystic", value: "hsl(213, 24%, 93%)", category: "Neutrals" },
  { name: "Mercury", value: "hsl(0, 0%, 91%)", category: "Neutrals" },
  { name: "Outer Space", value: "hsl(180, 3%, 19%)", category: "Neutrals" },
  { name: "Vivid", value: "hsl(16, 88%, 54%)", category: "Oranges" },
  { name: "Vivid Tangerine", value: "hsl(12, 100%, 74%)", category: "Reds" },
  { name: "Burnt Orange", value: "hsl(24, 100%, 41%)", category: "Oranges" },
  { name: "Ecstasy", value: "hsl(23, 95%, 52%)", category: "Oranges" },
  { name: "Jaffa", value: "hsl(22, 88%, 58%)", category: "Oranges" },
  { name: "Sandstorm", value: "hsl(42, 94%, 60%)", category: "Oranges" },
  { name: "Buttercup", value: "hsl(37, 90%, 51%)", category: "Oranges" },
  { name: "Carrot Orange", value: "hsl(28, 80%, 52%)", category: "Oranges" },
  { name: "Iris Blue", value: "hsl(187, 100%, 40%)", category: "Cyans" },
  { name: "Summer Sky", value: "hsl(200, 73%, 44%)", category: "Blues" },
  { name: "Hoki", value: "hsl(213, 23%, 51%)", category: "Blues" },
  { name: "Jordy Blue", value: "hsl(207, 83%, 75%)", category: "Blues" },
  { name: "Shark", value: "hsl(230, 8%, 15%)", category: "Neutrals" },
  { name: "Gin Fizz", value: "hsl(49, 100%, 94%)", category: "Neutrals" },
  { name: "Salomie", value: "hsl(50, 100%, 77%)", category: "Yellows" },
  { name: "Witch Haze", value: "hsl(55, 100%, 78%)", category: "Yellows" },
  { name: "Energy Yellow", value: "hsl(54, 89%, 64%)", category: "Yellows" },
  { name: "Goldenrod", value: "hsl(44, 96%, 71%)", category: "Oranges" },
  { name: "Yellow", value: "hsl(64, 100%, 50%)", category: "Yellows" },
  { name: "Candy Corn", value: "hsl(55, 99%, 69%)", category: "Yellows" },
  { name: "Cream", value: "hsl(60, 100%, 90%)", category: "Yellows" },
  { name: "Dolly", value: "hsl(60, 100%, 75%)", category: "Yellows" },
  { name: "Marigold Yellow", value: "hsl(61, 89%, 72%)", category: "Yellows" },
  { name: "Turbo", value: "hsl(56, 92%, 53%)", category: "Yellows" },
  { name: "Kournikova", value: "hsl(47, 94%, 66%)", category: "Yellows" },
  { name: "Cornflower Blue", value: "hsl(226, 92%, 63%)", category: "Blues" },
  { name: "Han Purple", value: "hsl(259, 96%, 46%)", category: "Purples" },
  { name: "Air Force Blue", value: "hsl(217, 47%, 52%)", category: "Blues" },
  { name: "Ripe Lemon", value: "hsl(48, 93%, 53%)", category: "Yellows" },
  { name: "Alice Blue", value: "hsl(210, 93%, 95%)", category: "Neutrals" },
  { name: "Orchid White", value: "hsl(60, 46%, 89%)", category: "Yellows" },
  { name: "Caribbean Green", value: "hsl(170, 97%, 40%)", category: "Cyans" },
  { name: "Silver Tree", value: "hsl(159, 43%, 59%)", category: "Cyans" },
  { name: "Downy", value: "hsl(173, 46%, 59%)", category: "Cyans" },
  { name: "Light Sea Green", value: "hsl(177, 72%, 37%)", category: "Cyans" },
  { name: "Medium Aquamarine", value: "hsl(150, 50%, 60%)", category: "Cyans" },
  { name: "Turquoise", value: "hsl(168, 67%, 53%)", category: "Cyans" },
  { name: "Madang", value: "hsl(116, 76%, 87%)", category: "Greens" },
  { name: "Riptide", value: "hsl(172, 61%, 71%)", category: "Cyans" },
  { name: "Shamrock", value: "hsl(145, 63%, 49%)", category: "Greens" },
  { name: "Mountain Meadow", value: "hsl(168, 76%, 36%)", category: "Cyans" },
  { name: "Emerald", value: "hsl(150, 52%, 51%)", category: "Cyans" },
  { name: "Gossip", value: "hsl(112, 50%, 66%)", category: "Greens" },
  { name: "Dark Sea Green", value: "hsl(126, 32%, 67%)", category: "Greens" },
  { name: "Jungles Green", value: "hsl(155, 67%, 45%)", category: "Cyans" },
  { name: "Malachite", value: "hsl(137, 100%, 45%)", category: "Greens" },
  { name: "Eucalyptus", value: "hsl(145, 63%, 40%)", category: "Greens" },
  { name: "Green Haze", value: "hsl(166, 99%, 30%)", category: "Cyans" },
  { name: "Free Speech Aquamarine", value: "hsl(163, 96%, 33%)", category: "Cyans" },
  { name: "Jade", value: "hsl(156, 100%, 35%)", category: "Cyans" },
  { name: "Salem", value: "hsl(148, 63%, 31%)", category: "Greens" },
  { name: "Observatory", value: "hsl(166, 95%, 30%)", category: "Cyans" },
  { name: "Summer Green", value: "hsl(129, 19%, 64%)", category: "Neutrals" },
  { name: "Puerto Rico", value: "hsl(176, 56%, 55%)", category: "Cyans" },
  { name: "Aqua Island", value: "hsl(166, 48%, 75%)", category: "Cyans" },
  { name: "Ocean Green", value: "hsl(149, 39%, 49%)", category: "Greens" },
  { name: "Light Green", value: "hsl(148, 78%, 71%)", category: "Greens" },
  { name: "Java", value: "hsl(167, 71%, 47%)", category: "Cyans" },
  { name: "Bright Turquoise", value: "hsl(166, 88%, 55%)", category: "Cyans" },
  { name: "Niagara", value: "hsl(167, 63%, 45%)", category: "Cyans" },
  { name: "Ebony Clay", value: "hsl(209, 30%, 19%)", category: "Blues" },
  { name: "Havelock Blue", value: "hsl(214, 65%, 55%)", category: "Blues" },
  { name: "Blue Jeans", value: "hsl(204, 71%, 62%)", category: "Blues" },
  { name: "Spray", value: "hsl(191, 61%, 69%)", category: "Cyans" },
  { name: "Shakespeare", value: "hsl(197, 64%, 59%)", category: "Blues" },
  { name: "Humming Bird", value: "hsl(190, 76%, 87%)", category: "Cyans" },
  { name: "Dodger Blue", value: "hsl(201, 87%, 54%)", category: "Blues" },
  { name: "Curious Blue", value: "hsl(204, 70%, 53%)", category: "Blues" },
  { name: "Madison", value: "hsl(210, 29%, 24%)", category: "Blues" },
  { name: "Deep Sky Blue", value: "hsl(199, 99%, 55%)", category: "Blues" },
  { name: "Chambray", value: "hsl(225, 46%, 42%)", category: "Blues" },
  { name: "Ming", value: "hsl(191, 41%, 34%)", category: "Cyans" },
  { name: "Jelly Bean", value: "hsl(204, 64%, 40%)", category: "Blues" },
  { name: "Sherpa Blue", value: "hsl(195, 97%, 13%)", category: "Blues" },
  { name: "San Marino", value: "hsl(218, 45%, 48%)", category: "Blues" },
  { name: "Malibu", value: "hsl(205, 82%, 68%)", category: "Blues" },
  { name: "Pickled Bluewood", value: "hsl(210, 29%, 29%)", category: "Blues" },
  { name: "Jacksons Purple", value: "hsl(226, 65%, 35%)", category: "Blues" },
  { name: "Fountain Blue", value: "hsl(204, 44%, 55%)", category: "Blues" },
  { name: "Wistful", value: "hsl(248, 33%, 74%)", category: "Purples" },
  { name: "Light Slate Blue", value: "hsl(265, 98%, 67%)", category: "Purples" },
  { name: "Scampi", value: "hsl(256, 20%, 50%)", category: "Purples" },
  { name: "Electric Purple", value: "hsl(273, 98%, 60%)", category: "Pinks" },
  { name: "Magnolia", value: "hsl(266, 92%, 95%)", category: "Neutrals" },
  { name: "Mauve", value: "hsl(265, 100%, 86%)", category: "Purples" },
  { name: "Electric Indigo", value: "hsl(271, 97%, 53%)", category: "Pinks" },
  { name: "Rebeccapurple", value: "hsl(270, 50%, 40%)", category: "Pinks" },
  { name: "Ce Soir", value: "hsl(296, 28%, 55%)", category: "Pinks" },
  { name: "Persian Blue", value: "hsl(258, 83%, 45%)", category: "Purples" },
  { name: "Lavender Purple", value: "hsl(268, 25%, 59%)", category: "Purples" },
  { name: "Honey Flower", value: "hsl(287, 27%, 35%)", category: "Pinks" },
  { name: "Medium Purple", value: "hsl(282, 80%, 63%)", category: "Pinks" },
  { name: "Grape Glimmer", value: "hsl(291, 30%, 83%)", category: "Pinks" },
  { name: "Studio", value: "hsl(282, 44%, 47%)", category: "Pinks" },
  { name: "Wisteria", value: "hsl(283, 39%, 53%)", category: "Pinks" },
  { name: "Light Wisteria", value: "hsl(281, 44%, 70%)", category: "Pinks" },
  { name: "Plum", value: "hsl(306, 41%, 40%)", category: "Special" },
  { name: "Seance", value: "hsl(291, 82%, 39%)", category: "Pinks" },
  { name: "Soft Red", value: "hsl(9, 81%, 61%)", category: "Reds" },
  { name: "Chestnut Rose", value: "hsl(355, 60%, 56%)", category: "Special" },
  { name: "Scarlet", value: "hsl(5, 90%, 51%)", category: "Reds" },
  { name: "Thunderbird", value: "hsl(2, 80%, 47%)", category: "Reds" },
  { name: "Old Brick", value: "hsl(6, 69%, 35%)", category: "Reds" },
  { name: "Valencia", value: "hsl(2, 65%, 55%)", category: "Reds" },
  { name: "Tall Poppy", value: "hsl(6, 63%, 46%)", category: "Reds" },
  { name: "Monza", value: "hsl(356, 100%, 41%)", category: "Special" },
  { name: "Carmine Pink", value: "hsl(6, 78%, 57%)", category: "Reds" },
  { name: "Razzmatazz", value: "hsl(337, 91%, 45%)", category: "Special" },
  { name: "Sunset Orange", value: "hsl(0, 91%, 62%)", category: "Reds" },
  { name: "Wax Flower", value: "hsl(7, 74%, 79%)", category: "Reds" },
  { name: "Cabaret", value: "hsl(339, 59%, 57%)", category: "Special" },
  { name: "New York Pink", value: "hsl(359, 60%, 69%)", category: "Special" },
  { name: "Radical Red", value: "hsl(345, 92%, 55%)", category: "Special" },
  { name: "Pomegranatte", value: "hsl(0, 86%, 57%)", category: "Reds" },
  { name: "Fire Bush", value: "hsl(32, 82%, 56%)", category: "Oranges" },
  { name: "Crusta", value: "hsl(16, 87%, 62%)", category: "Oranges" },
  { name: "Saffron Mango", value: "hsl(38, 94%, 66%)", category: "Oranges" },
  { name: "Cape Honey", value: "hsl(42, 96%, 82%)", category: "Oranges" },
  { name: "Confetti", value: "hsl(51, 76%, 65%)", category: "Yellows" }
];

export default FLAT_UI_COLORS;